---
apiVersion: v1
kind: Service
metadata:
  namespace: capstone
  name: preaply
  labels:
    app: preaply
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: preaply
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  name: preaply
  labels:
    app: preaply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preaply
  template:
    metadata:
      labels:
        app: preaply
    spec:
      containers:
        - name: preaply
          image: zasmin/hana-preaply:1.0
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                   key: KAFKA_BROKER
                   name: hanadream
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
